version: '3'
services:
  web:
    restart: always
    build: .
    command: "sh run.sh"
    ports:
      - "8000:8000"
    volumes:
      - .:/deploiement-vps
    env_file:
      - ".env"
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

